### ISSUE TITLE
Update set commit fails when deploying from git.

### ISSUE THREAD

**Issue by crysis88** [bmoers/sn-cicd#10]
When using git as the source for update set, update set is being loaded in target environment, but  commit fails because of scope errors. This happens both for scoped and global applications.
`Cannot commit Update Set 'Default' because: Update scope id '03852e7f4f613300a3cc121f9310c728' is different than update set scope id 'x_317910_latest28'. Resolve the problem before committing.`
Same update set works if i disable deployment from git.
Not sure it is related but i see below error in Logs:-
`GetKeys failed (com.glide.processors.soap.SOAPProcessingException: Web service not found: api/devops/cicd/source/sys_scope com.glide.processors.soap.SOAPProcessingException: Web service not found: api/devops/cicd/source/sys_scope`

**Comment by bmoers** [comment]
Will be fixed with 3.3.17

**Comment by crysis88** [comment]
I was debugging the update set deployment issue and seems like issue is, for update set scope name  is being used as  scope id, whereas in actual updates we have  different scope id (application  sys_id as scope id).
Setting update set scope id to application sys_id seems to fix the issue.
Sample Code changes in snClient.js.
` const getUpdateSetDetails = (updateSetSysId) => {
        return client.get({
            url: `api/${appPrefix}/cicd/updateset/${updateSetSysId}`,
            qs: {
                sysparm_display_value: 'all',
                sysparm_fields: 'sys_id, application.name, application.scope, application.sys_id, name, description, state, remote_sys_id, sys_created_by, sys_created_on, sys_updated_by, sys_updated_on'
            }
        }).then((result) => {
            if (!result.length)
                throw Error(`UpdateSet not found with ID ${updateSetSysId}`);

            var us = result[0];
            console.log('update set: ' + JSON.stringify(us));
            const updateSet = {
                sys_id: us.sys_id.value,
                appName: us['application.name'].display_value,
                scopeName: us['application.scope'].display_value,
                scopeId: us['application.sys_id'].value
            };`
Not sure if this is the correct fix, just wanted to share my findings.

**Comment by bmoers** [comment]
Thats correct! 
Will release a fix once all references to scopeId are tested.

**Comment by bmoers** [comment]
Fix released in https://github.com/bmoers/sn-cicd/releases/tag/v3.3.17
