### ISSUE TITLE
Issue When Building App - Install Node App fails

### ISSUE THREAD

**Issue by nci-snow-cicd** [bmoers/sn-cicd#30]
Install Node App steps fails as follow - Please advise.

[12:11:44.983] [LOG]    [10336]  Using SYS_* Field White-List 'sys_class_name, sys_created_by, sys_created_on, sys_id, sys_mod_count, sys_name, sys_package, sys_policy, sys_scope, sys_update_name, sys_updated_by, sys_updated_on'
[12:11:44.983] [LOG]    [10336]  Project Datastore: use remote
[12:11:44.985] [LOG]    [10336]  [/worker#ZbGaE-8YwQO-wT-JAAAA] build-project : install node application
[12:11:45.015] [LOG]    [10336]  install node app in C:\Users\user1\AppData\Local\Temp\3\git-root\459c6b10-47eb-4605-be75-f78bffe92478 [ 'ci', '--silent', '--no-audit', '--no-optional' ]
[12:11:55.729] [LOG]    [10336]  npm install process exited with code: 1
[12:11:55.730] [ERROR]  [10336]  [/worker#ZbGaE-8YwQO-wT-JAAAA] build-project : install node application failed:
 Error
    at C:\Users\user1\Documents\sncicd-server\node_modules\sn-cicd\lib\modules\build-project.js:41:76
    at tryCatcher (C:\Users\user1\Documents\sncicd-server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\user1\Documents\sncicd-server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\user1\Documents\sncicd-server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\user1\Documents\sncicd-server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\user1\Documents\sncicd-server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (C:\Users\user1\Documents\sncicd-server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\user1\Documents\sncicd-server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\user1\Documents\sncicd-server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\user1\Documents\sncicd-server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21) Error
    at C:\Users\user1\Documents\sncicd-server\node_modules\sn-cicd\lib\modules\build-project.js:41:76
    at tryCatcher (C:\Users\user1\Documents\sncicd-server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\user1\Documents\sncicd-server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\user1\Documents\sncicd-server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\user1\Documents\sncicd-server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\user1\Documents\sncicd-server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (C:\Users\user1\Documents\sncicd-server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\user1\Documents\sncicd-server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\user1\Documents\sncicd-server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\user1\Documents\sncicd-server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
[12:11:55.737] [LOG]    [10336]  [/worker#ZbGaE-8YwQO-wT-JAAAA] build-project : cleaning up project
[12:11:55.740] [LOG]    [10336]  deleting  C:\Users\user1\AppData\Local\Temp\3\git-root\459c6b10-47eb-4605-be75-f78bffe92478\node_modules
[12:11:57.512] [ERROR]  [10336]  [/worker#ZbGaE-8YwQO-wT-JAAAA] PROMISE JOB ERROR: Job 'buildProject' {
  type: 'exe',
  name: 'buildProject',
  options: 'xUauor5G8AKEmCLY',
  host: 'ncias-d2371-c',
  id: '0895740f-60fe-41ee-990b-09621667cfb5',
  emitter: { _events: {}, _eventsCount: 2 },
  created: 1586880704932,
  completed: null,
  workerId: '/worker#ZbGaE-8YwQO-wT-JAAAA',
  result: undefined,
  error: undefined

**Comment by bmoers** [comment]
Please navigate to C:\Users\user1\AppData\Local\Temp\3\git-root\459c6b10-47eb-4605-be75-f78bffe92478 and manually run `npm ci`
What kind of error does that throw?

**Comment by nci-snow-cicd** [comment]
Thank you for the reply; I actually was able to figure it out; had to downgrade the nodejs version from 12 to 10, deleted node_module and the package-lock.json; rebuilt the app - using npm install; then run; and the build completed successfully.

I am now running into a different issue where the Pull request is being raised; but no notification being recieved through slack even though I have it configured and enabled; I am not seeing the payload message being posted in the log screen and when I merge the pull request; nothing happens.

Can you please advise?

**Comment by bmoers** [comment]
Would you mind to share your .env file? You can send it in anonymised form to my email.

**Comment by nci-snow-cicd** [comment]
##
#  GitHub example integration related variables
#   -   used to raise pull requests in GitHub (not for GIT repo integration which is done via SSH)
##
# github credentials
CICD_PR_USER_NAME=nci-snow-cicd
# create an access token and grant it high privileges (https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line, resp. https://github.com/settings/tokens)
# required privileges are:
#   - repo
#   - admin:repo_hook
#   - admin:org_hook
#
CICD_PR_USER_PASSWORD=34130b9c8a3b20e91873b38bf143ff02a908109d
# ServiceNow host name. Name of the ServiceNow instance which acts as a proxy to route pull requests to this CICD server
#CICD_WEBHOOK_PROXY_SERVER=dev96952
CICD_WEBHOOK_PROXY_SERVER=service-sandbox.xxx.xxx.xxx
# Secret (see cicd-integration properties in ServiceNow)
CICD_WEBHOOK_SECRET=5VCSj9SPRH3EbNHrBSTf



## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
#

CICD_ORGANIZATION=service now customer

## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# WEB UI 
#
# FQDN of the CICD server under which the server is reachable in the network [localhost]
CICD_WEB_HOST_NAME=ncias-d2371-c.nci.nih.gov
# port under which the server is reachable in the network (for HTTP protocol) [8080]
CICD_WEB_HTTP_PORT=8080
# port under which the server runs locally. 
CICD_WEB_HTTP_PORT_INTERNAL=8080
# port under which the server is reachable in the network (port for HTTPS protocol). if enabled, requests to http:// are redirected  to https://
#CICD_WEB_HTTPS_PORT=8443
# port under which the server runs locally. 
#CICD_WEB_HTTPS_PORT_INTERNAL=8443
# to run a custom WEB-UI, point to custom web root [node-modules/sn-cicd/web']
CICD_WEB_DIR=

# HTTPS certificate information, [cert from '/cert' dir]
#CICD_WEB_HTTPS_KEY=D:\Users\jayakumars\Documents\GitHub\sn-cicd-working-copy\node_modules\sn-cicd\cert\server-key.pem
#CICD_WEB_HTTPS_CERT=D:\Users\jayakumars\Documents\GitHub\sn-cicd-working-copy\node_modules\sn-cicd\cert\server-crt.pem
#CICD_WEB_HTTPS_CA=D:\Users\jayakumars\Documents\GitHub\sn-cicd-working-copy\node_modules\sn-cicd\cert\server-ca-crt.pem

#CICD_WEB_HTTPS_KEY=/opt/cicd/cert/server-key.pem
#CICD_WEB_HTTPS_CERT=/opt/cicd/cert/server-crt.pem
#CICD_WEB_HTTPS_CA=/opt/cicd/cert/server-ca-crt.pem

# FQDN for Build-Process to connect to CICD server 
# set this in case the worker nodes are running on additional server (clustered setup)
# default to CICD_WEB_HOST_NAME:CICD_WEB_HTTP[S]_PORT - !!NOT synced with worker nodes!!
#CICD_GULP_HOST_FQDN=https://localhost:8443


# directory to place the nedb files [process.cwd()/'db']
#CICD_INTERNAL_DB_DIR=/opt/cicd/db

# directory to place the ServiceNow code extraction [temp/git-root]
#CICD_CODE_DIRECTORY=/opt/cicd/repos
# temp directory for zip extraction [temp/temp-build]
#CICD_TEMP_DIRECTORY=/opt/cicd/temp-build
# build results directory (static exposed under /doc) [temp/doc-root]
#CICD_DOC_DIRECTORY=/opt/cicd/doc-root

## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Proxy
#
# Proxy settings in case server runs behind a company proxy
#PROXY_HTTPS_PROXY=
#PROXY_STRICT_SSL=false


## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# EVENT BUS [WEBSOCKET]
#
# FQDN of the EventBus server to which the EventBus - Worker connect [localhost] - !!NOT synced with worker nodes!!
CICD_EB_HOST_NAME=localhost
# WebSocket port [4443]
CICD_EB_HOST_PORT=4443

# Event Bus Server settings (WebSockets), [cert from '/cert' dir]
#CICD_EB_HOST_SERVER_KEY=/opt/cicd//cert/eb-server-key.pem
#CICD_EB_HOST_SERVER_CERT=/opt/cicd/cert/eb-server-crt.pem
#CICD_EB_HOST_SERVER_CA=/opt/cicd/cert/eb-ca-crt.pem

# Event Bus Client settings (WebSockets), [cert from '/cert' dir] - !!NOT synced with worker nodes!!
#CICD_EB_HOST_CLIENT_KEY=/opt/cicd/cert/eb-client-key.pem 
#CICD_EB_HOST_CLIENT_CERT=/opt/cicd/cert/eb-client-crt.pem
#CICD_EB_HOST_CLIENT_CA=/opt/cicd/cert/eb-ca-crt.pem

# Number of workers to be stared [require('os').cpus().length]  - !!NOT synced with worker nodes!!
# If the server is started via pm2, set this to 0 and start app.js
#CICD_EB_WORKER_CLUSTER_NUM=2


## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# CODE EXPORT
#
# CICD API Prefix. If you have your own version of the 'CICD Integration' application in ServiceNow, name here the scope prefix
CICD_APP_PREFIX=
	# Run update set collision detection at first		
CICD_COLLISION_DETECTION_ENABLED=true
# toggle export records which do not contain JavaScript [true]
CICD_EXPORT_UNKNOWN_TYPES=true

# toggle to always crate .json files, this helps to better track changes [true]
CICD_EXPORT_ALL_AS_JSON=true

# treat empty fields as null values. ServiceNow does not allow to detect if a field is null or empty.
CICD_EXPORT_NULL_FOR_EMPTY=true

# only add following sys_* field in JSON files (helps reducing the noise in pull request)
CICD_EXPORT_SYS_FIELD_WHITELIST=sys_class_name, sys_created_by, sys_created_on, sys_id, sys_mod_count, sys_name, sys_package, sys_policy, sys_scope, sys_update_name, sys_updated_by, sys_updated_on


## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# SLACK INTEGRATION 
#
# toggle slack integration
CICD_SLACK_ENABLED=true
# webhook url
CICD_SLACK_WEBHOOK=https://hooks.slack.com/services/xxxxxx/
# override the channel of the webhook
#CICD_SLACK_CHANNEL_OVERRIDE=@user_name


	## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #		
# EMAIL INTEGRATION 		
#		
# toggle email integration		
CICD_EMAIL_ENABLED=false		
# the email server host name		
CICD_EMAIL_HOST=smtp.mail.com		
# the email server port		
CICD_EMAIL_PORT=587		
# credentials if required		
CICD_EMAIL_USER_NAME=
CICD_EMAIL_USER_PASSWORD=	
# use TLS		
CICD_EMAIL_SECURE=false		
# senders address		
CICD_EMAIL_FROM=			
# admin email address(es) to inform on deployment issues		
CICD_EMAIL_ADMINS=

## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# GIT 
#
# override the git settings normally used in run(application.git)
CICD_GIT_HOST=git@github.com:user1/
CICD_GIT_URL=https://github.com/user1/
# link to the branch template
CICD_GIT_BRANCH_LINK_TEMPLATE=${url}/tree/${branchName}

# override the system git user settings
#CICD_GIT_USER_NAME=git
#CICD_GIT_USER_EMAIL=git@git.com

# create a local git repo
CICD_GIT_ENABLED=true
# raise a pull request if build pass
CICD_GIT_PR_ENABLED=true
# delete update-set branch on merge
CICD_GIT_DELETE_BRANCH_ON_MERGE=true

# ---- Master Environment Mapping ---- 
# use below settings to hard-link a development environment to a production environment (master)
# if enabled, the 'git' information in the 'run' request from ServiceNow is not required.
#
# set this to 'true' to only allow to checkout fom master like specified below
CICD_GIT_STRICT_MASTER=false
#CICD_GIT_STRICT_MASTER=true
# default git master source (can be dangerous if you have multiple purpose instances. eg. IT and Finance)
CICD_GIT_MASTER_SOURCE=service-sandbox.xxx.xxx.xxx

# master source definition CICD_GIT_MASTER_SOURCE_[INSTANCENAME] (instance short name)
# this reads: if source is 'development.service-now.com', use 'prod.service-now.com' as the master
#CICD_GIT_MASTER_SOURCE_service-sandbox.nci.nih.gov=service-sandbox.nci.nih.gov
#CICD_GIT_MASTER_SOURCE_TESTING=prod.service-now.com
#CICD_GIT_MASTER_SOURCE_PREPROD=prod.service-now.com

#CICD_GIT_MASTER_SOURCE_dev96952=dev96952.service-now.com
#CICD_GIT_MASTER_SOURCE_TEST=stage7777.service-now.com
#CICD_GIT_MASTER_SOURCE_PREPROD=prod.service-now.com

## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# ATF
#
# in case puppeteer is configured to not automatically download chromium, 
# set this to a copy of chromium (see .npmrc)
#CICD_ATF_BROWSER=C:/temp/browsers/chrome-latest/chrome.exe
# run ATF test [true]
CICD_ATF_ENABLED=true

# set below to true if you want to see the puppeteer window (headless=false)
CICD_ATF_SHOW_BROWSER_WINDOW=false
# set this to false to protect ATF runs being executed on production environment (master env is seen as 'prod')
CICD_ATF_RUN_ON_PRODUCTION=false


## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# CREDENTIALS
#
# instance specific credentials can be set like
# CICD_[ATF]_[INSTANCENAME]_[TEST_USER_NAME]
# if not specified the default is used CICD_[ATF]_[TEST_USER_NAME]
CICD_ATF_TEST_USER_NAME=devops
CICD_ATF_TEST_USER_PASSWORD=xxxxxxxxx

# example for instance specific credentials
#CICD_ATF_TEST_INSTANCENAME_USER_NAME=
#CICD_ATF_TEST_INSTANCENAME_USER_PASSWORD=

# user to load update-set form 'source' and 'master'
CICD_CI_USER_NAME=devops
CICD_CI_USER_PASSWORD=xxxxxxxx

# example for instance specific credentials
#CICD_CI_INSTANCENAME_USER_NAME=CI-USER-NAME
#CICD_CI_INSTANCENAME_USER_PASSWORD=

# user to deploy update-set to 'target'
# this user must have the 'admin' role
CICD_CD_USER_NAME=devops
CICD_CD_USER_PASSWORD=xxxxxxxxx

# example for instance specific credentials
#CICD_CD_INSTANCENAME_USER_NAME=CD-USER-NAME
#CICD_CD_INSTANCENAME_USER_PASSWORD=


## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# BUILD
#
# se this to false if you run the build on a build server e.g. GitLabCi / Bamboo / Jenkins
CICD_EMBEDDED_BUILD=true
# access token to secure the /build api (a little bit)
CICD_BUILD_ACCESS_TOKEN=1Tnt2bx9mrVjxMQDfjhvRAYxiL9ldQN5ITR6DtM8T6Pq8YLbEjwAd60vmUiTIvSE


## # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# DEPLOY
#
# access token to secure the /deploy api (a little bit)
CICD_DEPLOY_ACCESS_TOKEN=Em5gEFz0acpVwbRWwfXNy0emDiJTG1MsL4KgkLn4EGsNpCHAS13yuTnLH48dgTrL

# automatically deploy update set to target if build pass (if CICD_GIT_PR_ENABLED is false)
CICD_CD_DEPLOY_ON_BUILD_PASS=false
# automatically deploy update set to target if pull request resolve
CICD_CD_DEPLOY_ON_PR_RESOLVE=true
# deploy update set from GIT repo instead from source service now environment
CICD_CD_DEPLOY_FROM_GIT=true

# ---- Deployment Environment Mapping ---- 
# use below settings to hard-link a source environment to a target environment
# if enabled, the 'target' information in the 'run' request from ServiceNow is not required.
#
# set this to 'true' to only deploy according to the below target definition
CICD_CD_STRICT_DEPLOYMENT=true
#CICD_CD_STRICT_DEPLOYMENT=false

# default deployment target (can be dangerous if you have multiple purpose instances. eg. IT and Finance)
CICD_CD_DEPLOYMENT_TARGET=service-dev2.xxx.xxx.xxx

#CICD_CD_DEPLOYMENT_TARGET=dev64637.service-now.com
# deployment target definition
#CICD_CD_DEPLOYMENT_TARGET_DEVINSTANCE=testcompany.service-now.com
#CICD_CD_DEPLOYMENT_TARGET_TESTINSTANCE=preprodcompany.service-now.com
#CICD_CD_DEPLOYMENT_TARGET_PREPRODINSTANCE=company.service-now.com

#CICD_CD_DEPLOYMENT_TARGET_dev96952=dev64721.service-now.com
#CICD_CD_DEPLOYMENT_TARGET_TEST=stage.servicenow.com
#CICD_CD_DEPLOYMENT_TARGET_PREPRODINSTANCE=company.service-now.com


# always deploy all changes captured over time in GIT in a merged way. This is identical to Application Deploy (from Store) in ServiceNow OOB		
# this setting can be overruled in the build payload (application.mergedDeployment in initial request).		
#		
# * requires CICD_CD_DEPLOY_FROM_GIT to be true		
CICD_CD_DEPLOY_ALWAYS_MERGED=true		
# always ensure the new records are deployed - even if there is a newer on the target environment 		
# this setting can be overruled in the build payload (application.forcedDeployment in initial request).		
#		
# * requires CICD_CD_DEPLOY_FROM_GIT to be true		
CICD_CD_DEPLOY_ALWAYS_OVERWRITE=false		
# records of this type will automatically be skipped on deployment conflicts		
# - changes coming in to a environment will be IGNORED if there is a newer change		
#		
# list of 'remote update' names STARTING with this string		
CICD_CD_DEPLOY_ALWAYS_SKIP_CONFLICTS=sys_properties,sys_data_source,ldap_server_config,sys_rest_message_fn,sys_soap_message_function		
# records of this type will automatically be ignored on deployment conflicts		
# - changes coming in to a environment will always be ACCEPTED regardless if there is a newer change		
#		
# list of 'remote update' names STARTING with this string		
CICD_CD_DEPLOY_ALWAYS_IGNORE_CONFLICTS=		
# don't stop deployment in case of delete of following types:		
#   sys_dictionary		
#   sys_db_object 		
#   var_dictionary		
#   svc_extension_variable		
#   wf_activity_variable		
#   atf_input_variable		
#   atf_output_variable		
#   sys_atf_variable		
#   sys_atf_remembered_values		
CICD_CD_DEPLOY_ALWAYS_IGNORE_DATA_LOSS=true

## Others
# on build tool set commit it to CICD_COMMIT_ID to have gulpfile.js access to the information in CICD server
# if not available, process will try to find last commit id via git (needs to be installed too on build server)
# CICD_COMMIT_ID=xxxx

**Comment by nci-snow-cicd** [comment]
[troubleshoot.txt](https://github.com/bmoers/sn-cicd/files/4478055/troubleshoot.txt)
[Log.txt](https://github.com/bmoers/sn-cicd/files/4478056/Log.txt)

**Comment by nci-snow-cicd** [comment]
[troubleshoot.txt](https://github.com/bmoers/sn-cicd/files/4478140/troubleshoot.txt)
[Log.txt](https://github.com/bmoers/sn-cicd/files/4478143/Log.txt)

**Comment by nci-snow-cicd** [comment]
[troubleshoot (1).txt](https://github.com/bmoers/sn-cicd/files/4478152/troubleshoot.1.txt)
[Log.txt](https://github.com/bmoers/sn-cicd/files/4478153/Log.txt)

**Comment by nci-snow-cicd** [comment]
[troubleshoot (1).txt](https://github.com/bmoers/sn-cicd/files/4478161/troubleshoot.1.txt)
[Log (1).txt](https://github.com/bmoers/sn-cicd/files/4478163/Log.1.txt)

**Comment by nci-snow-cicd** [comment]
sure attached are  both - The weird part is I receive messages for failed  builds - For example I tried changing the CICD_GIT_STRICT_MASTER=true, specified a default GIT_MASTER_SOURCE, kept the CICD_ATF_RUN_ON_PRODUCTION to false and got a failed build since ATF Run is disabled for Prod runs and the CICD process looks at the Default GIT Master source as being prod - I did get the slack notification for that; but for positive scenarios when every thing passes as shown in the log file; I am not seeing the Slack payload published in the log and not receiving the slack notification and of course can't pass this stage even if I manipulate the rest of the process from GitHub.

**Comment by bmoers** [comment]
You don't get a PR slack message as there is none ;)
https://github.com/bmoers/sn-cicd/blob/0b002a6d5f4920d1057540df6c2ad08a9806914d/lib/modules/build-complete.js#L81

Best you configure the GIT host to send a Slack message on PR

**Comment by nci-snow-cicd** [comment]
Thank you, Issue resolved, closing the ticket.

**Comment by bmoers** [comment]
> Thank you, Issue resolved, closing the ticket.

@nci-snow-cicd do you think it would make sense to integrate with slack here or is it sufficient to let the PR side do that?

**Comment by nci-snow-cicd** [comment]
yes it would; however - what I noticed is when the pull request is being published under the Webhook for the GitHub Repo created as part of the CICD run; the Webhook URL always appends the .service-now.com to the URL; so in my case my instance name has no ".service-now.com" in the link; it is a DNS name as follow: https://service-instance-dev.xxx.xxx.com so when the pull request is raised; it is raised with a web hook URL in the git repo as follow: https://service-instance-dev.xxx.xxx.com.service-now.com/api/devops/cicd/pull_request rather than: https://service-instance-dev.xxx.xxx.com/api/devops/cicd/pull_request - This was causing me an issue - so when repo is being created; I have to manually go the repo setting; Webhooks, remove the .-service-now.com from the Webhook URL and move on - And then I can start seeing the Webhook interactions for Slack for all the remaining phases. 

so the question here is if I have FQDN for my instance name that does not have ".service-now.com" in the host name; where do I change the code so the Github Webhook URL is generated without the ".service-now.com" - Please let me know.

**Comment by bmoers** [comment]
The webhook is created here:
https://github.com/bmoers/sn-cicd-example/blob/292c1b595f10a4394001e670093ac99c402fcfa0/cicd.js#L72, you can change that to your domain. 
But I think it would make sense to support custom domains as an option in the .env and use that instead on the whole server.
Are you using the "custom url" feature or have a self hosted env?

**Comment by nadimrizk83** [comment]
Thank you for considering both enhancements.  To answer your question, we're using the custom URL feature and our instances are not self hosted on-prem.

**Comment by bmoers** [comment]
Thanks
Seems not to be a big deal to implement #31 however it needs a change in the cicd-integration app https://github.com/bmoers/sn-cicd-integration/blob/81407229cc645228e718e7e69477e6c6ae19df6c/script_include/CiCdDeploy.js#L343

Would it be sufficient to compare the host across source and target (targetMatch[1] != targetMatch[2]) ?

**Comment by nadimrizk83** [comment]
Yes absolutely; If custom URL is used then there is no need to compare with the .service-now.com as long as the comparison is left at a generic level that should be sufficient.  This can be driven by the env variable set in the .env file (whether it is cutsom URL or default .service-now.com)

**Comment by bmoers** [comment]
Closing this as the custom domain feature is now official #31 and the example implementation updated https://github.com/bmoers/sn-cicd-example/commit/1241af9f672313c3c63e8b946945e58dee452d38
The messaging topic #32 I'll address when the MS Teams plugin is implemented.
