### ISSUE TITLE
CI User wasn't picked up when deploy update set

### ISSUE THREAD

**Issue by gitlabbin** [bmoers/sn-cicd#5]
Issue:
config snippet from .env file :
```
# user to load update-set form 'source' and 'master'
CICD_CI_USER_NAME=svc_cicd
CICD_CI_USER_PASSWORD=*****

# user to deploy update-set to 'target'
CICD_CD_USER_NAME=admin
CICD_CD_USER_PASSWORD=****
```
while running deployment jobs, it always using 'admin' to connect to the source instance, it will cause authentication failure
```
{ error:
   { message: 'User Not Authenticated',
     detail: 'Required to provide Auth information' },
  status: 'failure' }
```

**Comment by bmoers** [comment]
Fix in release >= 3.2.2

**Comment by gitlabbin** [comment]
Hi Boris,

Correct me if I am wrong:
`getCdClient` function is using only inside `deploy-update-set.js` for trigger a remote rest call,

```
return getCdClient(config).deployUpdateSet(config.updateSet.sys_id, targetHostName, {
                username: username,
                password: password
            })
```
No impact to the deployment inside of servicenow,  that is implemented in `sn-cicd-integration` project.

I did test on my side, everything working fine.

**Comment by bmoers** [comment]
The deployment is a series of calls. First one points to source which then (service now internally) connects to target to register a new update set source. 

Can you pls check on your target env what credentials are set here?
What roles does the CI user on source have?

Cheers
Boris

**Comment by bmoers** [comment]
The idea was to have as less admin grants as possible. For CI that’s no issue, but for CD it needs this privileges. 
If both users are admin this will for sure work. If only CD is, it won’t. 

I’m thinking of changing this API a bit to have all options.....

**Comment by gitlabbin** [comment]
You are right, I am using admin role for both, the rest api will update the source update set status to 'committed' too, so it will need privilege as well

**Comment by gitlabbin** [comment]
a new feature may need to encrypt the password, for some security policy reasons

**Comment by bmoers** [comment]
> a new feature may need to encrypt the password in side .env config, for some security policy reasons config file can't keep clear password.

If you don't want to have passwords in the .env file, you can set the env vars before startup of the service.

**Comment by bmoers** [comment]
As it needs a user which has admin or teamdev_user role I'm going to change the deployment API to look like this:

```
{
    "updateSetSysId": "xxxxxxxxxxxxxxxxxxxxxxxx",
    "targetEnvironment": { // the CD user of the target environment or fallback the CI user
        "host": "https://targethost.service-now.com",
        "username": "",
        "password": ""
    },
    "sourceEnvironment": {  // the CD user of the source environment or fallback the CI user
        "username": "",
        "password": ""
    }
}
```
'sourceEnvironment' will be used to create the 'update set source', the request to that API will be done with the CI user.

I'll keep the '_CICD_DEPLOYMENT_' creation part but will add a system property to toggle the creation of that user with 'teamdev_user' privileges. In that case there will be no need to have a CD user with admin role at all on the source environment.

**Comment by bmoers** [comment]
@gitlabbin 
Please have a look at the latest version and the updated documentation 
https://github.com/bmoers/sn-cicd-example-v3
and
https://github.com/bmoers/sn-cicd
The deployment process is now supporting GIT artefact checkout. So update sets get deployed directly from the GIT repo instead of a source environment.

I'm also going to present this tool on K19 Tuesday ~10:30 - in case you have plans to join the Knowledge.

Cheers
Boris

**Comment by gitlabbin** [comment]
Great job, I will find some time to try this new feature out.
Thanks @bmoers 👍

**Comment by gitlabbin** [comment]
@bmoers For "present this tool on K19 Tuesday ~10:30", any online conference can I join?  or some video available to watch in real time? 
quite exciting about that.
